export default {
  /* SAGAS EVENTS */
  // generic
  SAGA_ERROR: 'SAGA_ERROR',

  // auth
  SAGA_AUTH_ENDED: 'SAGA_AUTH_SUCCESS',
  SAGA_AUTH_RESPONSE: 'SAGA_AUTH_RESPONSE',
  SAGA_AUTH_LOGOUT: 'SAGA_AUTH_LOGOUT',
  SAGA_AUTH_FACEBOOK_RESPONSE: 'SAGA_AUTH_FACEBOOK_RESPONSE',

  // createEvent
  SAGA_CREATE_EVENT_THUMBNAIL_PROCESSED: 'SAGA_CREATE_EVENT_THUMBNAIL_PROCESSED',

  // map
  SAGA_MAP_MARKERS_SET: 'SAGA_MAP_MARKERS_SET',

  // newsfeed
  SAGA_NEWSFEED_RESPONSE: 'SAGA_NEWSFEED_RESPONSE',
  SAGA_NEWSFEED_PAST_RESPONSE: 'SAGA_NEWSFEED_PAST_RESPONSE',
  SAGA_NEWSFEED_LIVE_RESPONSE: 'SAGA_NEWSFEED_LIVE_RESPONSE',
  SAGA_NEWSFEED_UPCOMING_RESPONSE: 'SAGA_NEWSFEED_UPCOMING_RESPONSE',

  // register
  SAGA_REGISTER_RESPONSE: 'SAGA_REGISTER_RESPONSE',

  // streams
  SAGA_STREAMS_REQUEST: 'SAGA_STREAMS_REQUEST',
  SAGA_STREAMS_RESPONSE: 'SAGA_STREAMS_RESPONSE',
  SAGA_STREAMS_PAST_RESPONSE: 'SAGA_STREAMS_PAST_RESPONSE',
  SAGA_STREAMS_LIVE_RESPONSE: 'SAGA_STREAMS_LIVE_RESPONSE',
  SAGA_STREAMS_UPCOMING_RESPONSE: 'SAGA_STREAMS_UPCOMING_RESPONSE',
  SAGA_STREAMS_SUBSCRIBERS_RESPONSE: 'SAGA_STREAMS_SUBSCRIBERS_RESPONSE',
  SAGA_STREAMS_SUBSCRIBE_RESPONSE: 'SAGA_STREAMS_SUBSCRIBE_RESPONSE',
  SAGA_STREAMS_UNSUBSCRIBE_RESPONSE: 'SAGA_STREAMS_UNSUBSCRIBE_RESPONSE',

  // users
  SAGA_USERS_FOLLOWING_RESPONSE: 'SAGA_USERS_FOLLOWING_RESPONSE',
  SAGA_USERS_FOLLOW_USER_RESPONSE: 'SAGA_USERS_FOLLOW_USER_RESPONSE',
  SAGA_USERS_UNFOLLOW_USER_RESPONSE: 'SAGA_USERS_UNFOLLOW_USER_RESPONSE',

  /* UI EVENTS */
  // Component agnostic
  UI_CURRENT_LANGUAGE_SET: 'UI_CURRENT_LANGUAGE_SET',
  UI_USER_FOLLOWED: 'UI_USER_FOLLOWED',
  UI_USER_UNFOLLOWED: 'UI_USER_UNFOLLOWED',
  UI_ERROR_MODAL_OPENED: 'UI_ERROR_MODAL_OPENED',
  UI_ERROR_MODAL_CLOSED: 'UI_ERROR_MODAL_CLOSED',

  // Auth
  UI_AUTH_OUTSIDE_CLICKED: 'UI_AUTH_OUTSIDE_CLICKED',
  UI_AUTH_USERMENU_LOGOUT_CLICKED: 'UI_AUTH_USERMENU_LOGOUT_CLICKED',
  UI_AUTH_FACEBOOK_CLICKED: 'UI_AUTH_FACEBOOK_CLICKED',

  // CreateEvent
  UI_CREATE_EVENT_CLOSED: 'UI_CREATE_EVENT_CLOSED',
  UI_CREATE_EVENT_FILES_DROPPED: 'UI_CREATE_EVENT_FILES_DROPPED',
  UI_CREATE_EVENT_LOCATION_CHANGED: 'UI_CREATE_EVENT_LOCATION_CHANGED',
  UI_CREATE_EVENT_DATE_CHANGED: 'UI_CREATE_EVENT_DATE_CHANGED',
  UI_CREATE_EVENT_OUTSIDE_CLICKED: 'UI_CREATE_EVENT_OUTSIDE_CLICKED',
  UI_CREATE_EVENT_SUBMITTED: 'UI_CREATE_EVENT_SUBMITTED',
  UI_CREATE_EVENT_SUGGEST_SELECTED: 'UI_CREATE_EVENT_SUGGEST_SELECTED',

  // LoginForm
  UI_LOGIN_FORM_SUBMITTED: 'UI_LOGIN_FORM_SUBMITTED',

  // Main
  UI_MAIN_CREATE_EVENT_BUTTON_CLICKED: 'UI_MAIN_CREATE_EVENT_BUTTON_CLICKED',

  // Map
  UI_MAP_LOADED: 'UI_MAP_LOADED',
  UI_MAP_MOVED: 'UI_MAP_MOVED',
  UI_MAP_MARKER_POPUP_TITLE_CLICKED: 'UI_MAP_MARKER_POPUP_TITLE_CLICKED',

  // Newsfeed
  UI_NEWSFEED_BUTTON_CLICKED: 'UI_NEWSFEED_BUTTON_CLICKED',
  UI_NEWSFEED_OPENED: 'UI_NEWSFEED_OPENED',
  UI_NEWSFEED_ROW_TITLE_CLICKED: 'UI_NEWSFEED_ROW_TITLE_CLICKED',
  UI_NEWSFEED_OUTSIDE_CLICKED: 'UI_NEWSFEED_OUTSIDE_CLICKED',

  // NewsfeedFilter
  UI_NEWSFEED_FILTER_LIVE_CLICKED: 'UI_NEWSFEED_FILTER_LIVE_CLICKED',
  UI_NEWSFEED_FILTER_PAST_CLICKED: 'UI_NEWSFEED_FILTER_PAST_CLICKED',
  UI_NEWSFEED_FILTER_UPCOMING_CLICKED: 'UI_NEWSFEED_FILTER_UPCOMING_CLICKED',

  // Search
  UI_SEARCH_BUTTON_CLICKED: 'UI_SEARCH_BUTTON_CLICKED',

  // SearchBar
  UI_SEARCH_BAR_SUGGEST_SELECTED: 'UI_SEARCH_BAR_SUGGEST_SELECTED',
  UI_SEARCH_BAR_OUTSIDE_CLICKED: 'UI_SEARCH_BAR_OUTSIDE_CLICKED',
  UI_SEARCH_BAR_CHANGED: 'UI_SEARCH_BAR_CHANGED',

  // SignupForm
  UI_SIGNUP_FORM_SUBMITTED: 'UI_SIGNUP_FORM_SUBMITTED',

  // Stream
  UI_STREAM_CLOSED: 'UI_STREAM_CLOSED',
  UI_STREAM_OPENED: 'UI_STREAM_OPENED',
  UI_STREAM_SUBSCRIBED: 'UI_STREAM_SUBSCRIBED',
  UI_STREAM_UNSUBSCRIBED: 'UI_STREAM_UNSUBSCRIBED',

  // StreamFilter
  UI_STREAM_FILTER_LIVE_CLICKED: 'UI_STREAM_FILTER_LIVE_CLICKED',
  UI_STREAM_FILTER_PAST_CLICKED: 'UI_STREAM_FILTER_PAST_CLICKED',
  UI_STREAM_FILTER_UPCOMING_CLICKED: 'UI_STREAM_FILTER_UPCOMING_CLICKED',

  // StreamList
  UI_STREAM_LIST_ROW_CLICKED: 'UI_STREAM_LIST_ROW_CLICKED',

  // Header
  UI_HEADER_SIGNIN_BUTTON_CLICKED: 'UI_HEADER_SIGNIN_BUTTON_CLICKED'
}
